name: Code Coverage

on: [push, pull_request]

jobs:
    build:
        name: Run Code Coverage
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: 18
    
          - name: Install dependencies
            run: npm install
          - name: Run tests
            run: npm test
          - name: Run Code Coverage
            uses: codecov/codecov-action@v4.0.1
            with:
                token: ${{ secrets.CODECOV_TOKEN }}
